-- Phase 2: faceless-video production on the same approval rails.
--
-- A `video_production` turns an approved script (agent_job) into a production
-- package: a tightened voiceover script, a scene/b-roll plan, a title, and a
-- thumbnail concept (generated by the Producer agent — Claude). Rendering the
-- actual video is a delegated backend (stub now; Blotato/vidIQ later). The
-- operator approves the package before it can be distributed — judgment stays
-- human, and the approved video flows out via the Blotato mediaUrls path.

create table if not exists video_production (
  id                uuid primary key default gen_random_uuid(),
  job_id            uuid references agent_job (id) on delete set null,  -- source script
  venture_id        uuid references venture (id) on delete set null,
  script            text not null default '',     -- snapshot of the source script
  title             text not null default '',
  voiceover_script  text not null default '',
  scene_plan        text not null default '[]',   -- JSON array of scene/b-roll lines
  thumbnail_concept text not null default '',
  video_url         text,                          -- the rendered asset (delegated)
  backend           text,                          -- which render backend produced it
  status            text not null default 'draft'
                    check (status in ('draft', 'awaiting_approval', 'approved', 'rejected', 'failed')),
  error             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists video_production_status_idx on video_production (status);

-- A publication can now carry a video production (with media) instead of just a
-- text job. Loosen job_id to nullable and add the production link + media URLs.
alter table publication alter column job_id drop not null;
alter table publication
  add column if not exists production_id uuid references video_production (id) on delete cascade;
alter table publication
  add column if not exists media_urls text not null default '[]';  -- JSON array
